### ISSUE TITLE
Checklist to MVP

### ISSUE THREAD

**Issue by thisisparker** [thisisparker/cursewords#1]
This thing kind of works! It's been tested on multiple platforms and with variegated input. These are the features still left to implement before an MVP.

- [x] Saving progress on a puzzle
- [x] Go to numbered square
- [x] Control all of the above with ctrl+ commands, displayed in some kind of status bar

At that point, I'll need to put together:
- [x] A README file
- [x] A license
- [x] Pip packaging

Considered but not included in this list are a few other things. For later:
- [x] Pausing a puzzle
- [x] Timer
- [x] Check puzzle
- [x] Reveal answers

**Comment by thisisparker** [comment]
Oh also: docstrings and probably a good solid refactor.

**Comment by thisisparker** [comment]
I might push the timer to a future release. Not only is it a little tricky to implement while running, but I realized I can't save the time data in the `.puz` file itself (in case solving takes more than one session) so I will have to come up with a solution for that later.

That probably also means pausing is non-essential for an MVP! Given that I've got saving and ctrl+ commands working, that leaves, basically

- Go to numbered square command
- Better status bar

**Comment by thisisparker** [comment]
It turns out you can save the time data in the `.puz` and I think I'm going to! I had to wrestle a bit with the library to figure it out, but once I got it saving the "markup" information (like whether a box had been checked, etc) in that file, I figured out how to access those additional fields.

**Comment by thisisparker** [comment]
:tada:
